name: CMake Build

on: [push, pull_request]

jobs:
  build:
    name: unwiished_dat_tool-${{ matrix.os-name }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os-name: linux
            build_type: Release
          - os: windows-latest  
            os-name: windows
            build_type: Release
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code WITH submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install deps (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cmake --build build --config ${{ matrix.build_type }}
        
    - name: Upload Windows Artifacts
      if: matrix.os-name == 'windows'
      uses: actions/upload-artifact@v4
      with:
        name: unwiished_dat_tool-${{ matrix.os-name }}-${{ matrix.build_type }}
        path: |
          build/Release/**
        retention-days: 1

    - name: Upload Linux Artifacts
      if: matrix.os-name == 'linux'
      uses: actions/upload-artifact@v4
      with:
        name: unwiished_dat_tool-${{ matrix.os-name }}-${{ matrix.build_type }}
        path: |
          build/**
        retention-days: 1